_target_: pytorch_lightning.Trainer

accelerator: "gpu"
precision: 16
devices: 3
min_epochs: 1
max_epochs: 4

val_check_interval: 0.5

strategy: "ddp_find_unused_parameters_true"

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 1
