_target_: src.datamodules.hf_datamodule.HFDataModule

dataset_name: "ncbi_disease,bc4chemd_ner,bc2gm_corpus,linnaeus" # override in your experiment! should be foldername inside data/
data_dir: ${data_dir}
tokenizer_name: ${model.huggingface_model}
hf_token: "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"
max_length: 128  
batch_size: 32
num_workers: 8
pin_memory: True