_target_: src.datamodules.hf_datamodule.HFDataModule

dataset_name: "ncbi_disease,drAbreu/bc4chemd_ner,bc2gm_corpus,linnaeus" # override in your experiment! should be foldername inside data/
tokenizer_name: ${model.huggingface_model}
hf_token: "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"
max_length: 4096  
batch_size: 128
num_workers: 8
pin_memory: True